### ISSUE TITLE
Shared memory?

### ISSUE THREAD

**Issue by jonalf** [MichaelRobertson479/kuangNan_robertsonMic_shauEri#1]
The idea is approved, but you make note of using IPC concepts like shared memory when you are designing. a networked based game to be run on multiple computers. Please update your design with a clarification or new implementation.

**Comment by MichaelRobertson479** [comment]
Instead of networking, we will have players SSH onto a single device. We will then use shared memory to keep track of whose turn it is, what card was just played, and to allow only a certain amount of people to join the game (see below for full details about "networking"). We will also use semaphores to allow write access to the file representing the entire pile of cards, which we need mainly to account for stacked draw cards.

**Shared Memory Variables:**
- turnCount
- numberOfPlayers / players (one changes, one stays constant)
- playerNumber

**Local Variables:**
- myNumber

**Pseudo Code:**
Init Function:
- Set up hand, deck, etc.
- Create/get shared memory
- If numberOfPlayers was just created:
      - Assign (same) value to numberOfPlayers and players based on user input
      - Set myNumber to 1 (indicating player 1)
      - Set playerNumber to 2 (will be used by next player to join)
      - Decrease numberOfPlayers by 1
      - Set turnCount to 1 (first turn)
-  Else if numberOfPlayers is 0 (everyone has already joined):
      - Print "Game is full"
      - Quit program
- Else
      - Copy the value of playerNumber into myNumber
      - Increase playerNumber by 1 (for the next player)
      - Decrease numberOfPlayers by 1 (counting down until everyone joined)

Main Function:
- Shtuff...
- While the win condition isn't met by anyone yet:
      - Get turnCount value from shared memory
      - If (turnCount % players) equals myNumber:
            - Play card, draw, etc.
            - Change turnCount appropriately (usually just add 1, but may need to add 2 for skips, or start 
              subtracting in the case of a reverse card, which we may need another shared memory 
              variable for)

**Comment by jonalf** [comment]
approved

make it so
